# Generated by Django 3.2.25 on 2026-04-21 16:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RunBladePrice',
            fields=[
                ('id', models.BigAutoField(help_text='Id', primary_key=True, serialize=False, verbose_name='Id')),
                ('description', models.CharField(blank=True, help_text='描述', max_length=255, null=True, verbose_name='描述')),
                ('modifier', models.CharField(blank=True, help_text='修改人', max_length=255, null=True, verbose_name='修改人')),
                ('dept_belong_id', models.CharField(blank=True, help_text='数据归属部门', max_length=255, null=True, verbose_name='数据归属部门')),
                ('update_datetime', models.DateTimeField(auto_now=True, help_text='修改时间', null=True, verbose_name='修改时间')),
                ('create_datetime', models.DateTimeField(auto_now_add=True, help_text='创建时间', null=True, verbose_name='创建时间')),
                ('business_type', models.CharField(choices=[('跑刀', '跑刀'), ('跑手', '跑手')], max_length=20, verbose_name='业务类型')),
                ('grid_type', models.CharField(choices=[('9格', '9格'), ('6格', '6格'), ('4格', '4格'), ('2格', '2格'), ('4-6格', '4-6格')], max_length=20, verbose_name='物品格子')),
                ('unit_price', models.CharField(blank=True, max_length=50, null=True, verbose_name='单人单价(R)')),
                ('rmb', models.FloatField(default=0, verbose_name='人民币R')),
                ('game_money', models.CharField(blank=True, max_length=50, null=True, verbose_name='对应游戏币')),
                ('remark', models.CharField(blank=True, max_length=200, null=True, verbose_name='备注说明')),
                ('creator', models.ForeignKey(db_constraint=False, help_text='创建人', null=True, on_delete=django.db.models.deletion.SET_NULL, related_query_name='creator_query', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
            ],
            options={
                'verbose_name': '三角洲跑刀跑手价格',
                'verbose_name_plural': '三角洲跑刀跑手价格',
                'ordering': ['business_type', 'grid_type'],
            },
        ),
    ]
