# Generated by Django 3.2.3 on 2025-11-14 22:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='envinfo',
            table='base_envinfo',
        ),
        migrations.AlterModelTable(
            name='moduleinfo',
            table='base_moduleinfo',
        ),
        migrations.AlterModelTable(
            name='projectinfo',
            table='base_projectinfo',
        ),
    ]
