# Generated by Django 3.2.3 on 2025-11-15 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20251114_2259'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EnvInfo',
        ),
    ]