# Generated by Django 3.2.3 on 2025-11-15 17:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0003_auto_20251115_0919'),
    ]

    operations = [
        migrations.CreateModel(
            name='UITestCase',
            fields=[
                ('id', models.BigAutoField(help_text='Id', primary_key=True, serialize=False, verbose_name='Id')),
                ('description', models.CharField(blank=True, help_text='描述', max_length=255, null=True, verbose_name='描述')),
                ('modifier', models.CharField(blank=True, help_text='修改人', max_length=255, null=True, verbose_name='修改人')),
                ('dept_belong_id', models.CharField(blank=True, help_text='数据归属部门', max_length=255, null=True, verbose_name='数据归属部门')),
                ('update_datetime', models.DateTimeField(auto_now=True, help_text='修改时间', null=True, verbose_name='修改时间')),
                ('create_datetime', models.DateTimeField(auto_now_add=True, help_text='创建时间', null=True, verbose_name='创建时间')),
                ('name', models.CharField(max_length=100, verbose_name='用例名称')),
                ('yaml_file', models.FileField(blank=True, null=True, upload_to='uitest/yaml/', verbose_name='YAML文件')),
                ('case_type', models.IntegerField(choices=[(0, 'web'), (1, 'android'), (2, 'ios')], verbose_name='用例类型')),
                ('creator', models.ForeignKey(db_constraint=False, help_text='创建人', null=True, on_delete=django.db.models.deletion.SET_NULL, related_query_name='creator_query', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('module_belong', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.moduleinfo', verbose_name='所属模块')),
                ('project_belong', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.projectinfo', verbose_name='所属项目')),
            ],
            options={
                'verbose_name': 'UI测试用例',
                'verbose_name_plural': 'UI测试用例',
                'db_table': 'uitest_case',
            },
        ),
        migrations.CreateModel(
            name='UITestReport',
            fields=[
                ('id', models.BigAutoField(help_text='Id', primary_key=True, serialize=False, verbose_name='Id')),
                ('description', models.CharField(blank=True, help_text='描述', max_length=255, null=True, verbose_name='描述')),
                ('modifier', models.CharField(blank=True, help_text='修改人', max_length=255, null=True, verbose_name='修改人')),
                ('dept_belong_id', models.CharField(blank=True, help_text='数据归属部门', max_length=255, null=True, verbose_name='数据归属部门')),
                ('update_datetime', models.DateTimeField(auto_now=True, help_text='修改时间', null=True, verbose_name='修改时间')),
                ('create_datetime', models.DateTimeField(auto_now_add=True, help_text='创建时间', null=True, verbose_name='创建时间')),
                ('report', models.TextField(blank=True, help_text='报告本地路径', null=True, verbose_name='报告本地路径')),
                ('report_file', models.TextField(blank=True, help_text='报告内容', null=True, verbose_name='报告内容')),
                ('case_type', models.IntegerField(choices=[(0, 'web'), (1, 'android'), (2, 'ios')], default=0, help_text='用例类型', verbose_name='用例类型')),
                ('result', models.IntegerField(choices=[(0, '失败'), (1, '成功')], default=1, help_text='结果', verbose_name='结果')),
                ('case_belong', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uitest.uitestcase', verbose_name='关联用例')),
                ('creator', models.ForeignKey(db_constraint=False, help_text='创建人', null=True, on_delete=django.db.models.deletion.SET_NULL, related_query_name='creator_query', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('module_belong', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.moduleinfo', verbose_name='所属模块')),
                ('project_belong', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.projectinfo', verbose_name='所属项目')),
            ],
            options={
                'verbose_name': 'UI测试报告',
                'verbose_name_plural': 'UI测试报告',
                'db_table': 'uitest_report',
            },
        ),
    ]
