# Generated by Django 3.2.3 on 2025-11-21 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uitest', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uitestcase',
            name='yaml_file',
            field=models.TextField(blank=True, default='', help_text='yaml文件', null=True, verbose_name='yaml文件'),
        ),
    ]
