# Generated by Django 3.2.3 on 2025-11-21 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uitest', '0002_alter_uitestcase_yaml_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uitestcase',
            name='yaml_file',
            field=models.FileField(blank=True, default='', help_text='yaml文件', null=True, upload_to='', verbose_name='yaml文件'),
        ),
    ]
