# Generated by Django 3.2.3 on 2025-11-22

from django.db import migrations


def convert_empty_strings_to_null(apps, schema_editor):
    """将yaml_file_id字段中的空字符串转换为NULL"""
    UITestCase = apps.get_model('uitest', 'UITestCase')
    for case in UITestCase.objects.all():
        if hasattr(case, 'yaml_file_id') and case.yaml_file_id == '':
            case.yaml_file_id = None
            case.save()


class Migration(migrations.Migration):

    dependencies = [
        ('uitest', '0005_alter_uitestcase_yaml_file'),
    ]

    operations = [
        migrations.RunPython(convert_empty_strings_to_null),
    ]
