# Generated by Django 3.2.3 on 2025-11-22

from django.db import migrations, models


def convert_empty_strings_to_null(apps, schema_editor):
    """将yaml_file字段中的空字符串转换为NULL"""
    UITestCase = apps.get_model('uitest', 'UITestCase')
    # 更新所有空字符串值为NULL
    for case in UITestCase.objects.all():
        if hasattr(case, 'yaml_file_id') and case.yaml_file_id == '':
            case.yaml_file_id = None
            case.save()


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0001_initial'),
        ('uitest', '0006_auto_20251122_1522'),
    ]

    operations = [
        # 先清理数据，将空字符串转换为NULL
        migrations.RunPython(convert_empty_strings_to_null),
        # 然后修改字段类型
        migrations.AlterField(
            model_name='uitestcase',
            name='yaml_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=models.SET_NULL,
                                    to='system.filelist', verbose_name='YAML文件'),
        ),
    ]