# Generated by Django 3.2.3 on 2025-11-22 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0001_initial'),
        ('uitest', '0008_alter_yaml_file_to_foreignkey'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uitestcase',
            name='yaml_file',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='system.filelist', verbose_name='YAML文件'),
        ),
    ]
