# Generated by Django 3.2.3 on 2025-11-22 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uitest', '0009_alter_uitestcase_yaml_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uitestcase',
            name='yaml_file',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='文件名称'),
        ),
    ]
