# Generated by Django 3.2.3 on 2025-11-22 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uitest', '0010_alter_uitestcase_yaml_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uitestreport',
            old_name='report',
            new_name='report_path',
        ),
        migrations.RemoveField(
            model_name='uitestreport',
            name='report_file',
        ),
    ]
