# Generated by Django 3.2.3 on 2025-11-23 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uitest', '0011_auto_20251122_2117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uitestcase',
            name='yaml_file',
            field=models.FileField(blank=True, null=True, upload_to='uitest/yaml/', verbose_name='YAML文件'),
        ),
    ]
