# Generated by Django 3.2.25 on 2026-02-05 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uitest', '0012_alter_uitestcase_yaml_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uitestcase',
            name='yaml_file',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to='uitest/yaml/', verbose_name='YAML文件'),
        ),
    ]
