# Generated by Django 3.2.25 on 2026-02-05 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uitest', '0013_alter_uitestcase_yaml_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uitestcase',
            name='yaml_file',
            field=models.TextField(blank=True, null=True, verbose_name='YAML文件'),
        ),
    ]
