# Generated by Django 3.2.25 on 2026-04-20 13:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('uitest', '0014_alter_uitestcase_yaml_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessRecord',
            fields=[
                ('id', models.BigAutoField(help_text='Id', primary_key=True, serialize=False, verbose_name='Id')),
                ('description', models.CharField(blank=True, help_text='描述', max_length=255, null=True, verbose_name='描述')),
                ('modifier', models.CharField(blank=True, help_text='修改人', max_length=255, null=True, verbose_name='修改人')),
                ('dept_belong_id', models.CharField(blank=True, help_text='数据归属部门', max_length=255, null=True, verbose_name='数据归属部门')),
                ('update_datetime', models.DateTimeField(auto_now=True, help_text='修改时间', null=True, verbose_name='修改时间')),
                ('create_datetime', models.DateTimeField(auto_now_add=True, help_text='创建时间', null=True, verbose_name='创建时间')),
                ('wechat_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='微信号')),
                ('demand', models.CharField(blank=True, max_length=200, null=True, verbose_name='需求')),
                ('quantity', models.PositiveIntegerField(blank=True, null=True, verbose_name='数量')),
                ('contact', models.CharField(blank=True, max_length=100, null=True, verbose_name='联系方式')),
                ('collision_platform', models.CharField(blank=True, max_length=100, null=True, verbose_name='撞车平台')),
                ('shipment_platform', models.CharField(blank=True, max_length=100, null=True, verbose_name='出货平台')),
                ('payment_method', models.CharField(blank=True, max_length=50, null=True, verbose_name='付款方式')),
                ('is_paid', models.BooleanField(default=False, verbose_name='是否付款')),
                ('price_payable', models.FloatField(blank=True, default=0, null=True, verbose_name='应付价格')),
                ('price_actual', models.FloatField(blank=True, default=0, null=True, verbose_name='实付价格')),
                ('platform_deduct', models.FloatField(blank=True, default=0, null=True, verbose_name='平台扣除')),
                ('cost_deduct', models.FloatField(blank=True, default=0, null=True, verbose_name='成本扣除')),
                ('redpacket', models.FloatField(blank=True, default=0, null=True, verbose_name='红包')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('profit', models.FloatField(blank=True, null=True, verbose_name='盈余')),
                ('monthly_receipt', models.FloatField(blank=True, null=True, verbose_name='月实收(流水)')),
                ('monthly_platform_deduct', models.FloatField(blank=True, default=0, null=True, verbose_name='月平台总扣除')),
                ('monthly_cost_total', models.FloatField(blank=True, default=0, null=True, verbose_name='月成本总')),
                ('monthly_profit_total', models.FloatField(blank=True, default=0, null=True, verbose_name='月总盈余')),
                ('total_platform_deduct', models.FloatField(blank=True, default=0, null=True, verbose_name='平台总扣除')),
                ('total_cost_all', models.FloatField(blank=True, default=0, null=True, verbose_name='成本总')),
                ('total_profit_all', models.FloatField(blank=True, default=0, null=True, verbose_name='总盈余')),
                ('record_date', models.DateField(auto_now_add=True, verbose_name='业务日期')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('creator', models.ForeignKey(db_constraint=False, help_text='创建人', null=True, on_delete=django.db.models.deletion.SET_NULL, related_query_name='creator_query', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
            ],
            options={
                'verbose_name': '业务数据登记',
                'verbose_name_plural': '业务数据登记',
                'ordering': ['-record_date'],
            },
        ),
        migrations.RemoveField(
            model_name='uitestreport',
            name='case_belong',
        ),
        migrations.RemoveField(
            model_name='uitestreport',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='uitestreport',
            name='module_belong',
        ),
        migrations.RemoveField(
            model_name='uitestreport',
            name='project_belong',
        ),
        migrations.DeleteModel(
            name='UITestCase',
        ),
        migrations.DeleteModel(
            name='UITestReport',
        ),
    ]
