# Generated by Django 3.2.25 on 2026-04-20 16:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EscortPrice',
            fields=[
                ('id', models.BigAutoField(help_text='Id', primary_key=True, serialize=False, verbose_name='Id')),
                ('description', models.CharField(blank=True, help_text='描述', max_length=255, null=True, verbose_name='描述')),
                ('modifier', models.CharField(blank=True, help_text='修改人', max_length=255, null=True, verbose_name='修改人')),
                ('dept_belong_id', models.CharField(blank=True, help_text='数据归属部门', max_length=255, null=True, verbose_name='数据归属部门')),
                ('update_datetime', models.DateTimeField(auto_now=True, help_text='修改时间', null=True, verbose_name='修改时间')),
                ('create_datetime', models.DateTimeField(auto_now_add=True, help_text='创建时间', null=True, verbose_name='创建时间')),
                ('package_type', models.CharField(choices=[('体验单', '体验单'), ('绝密监狱航天', '绝密监狱航天'), ('绝密巴克什', '绝密巴克什'), ('赌约单', '赌约单')], max_length=50, verbose_name='套餐类型')),
                ('package_name', models.CharField(max_length=200, verbose_name='套餐名称')),
                ('sell_price', models.FloatField(default=0, verbose_name='出售价格(R)')),
                ('guarantee_money', models.FloatField(default=0, verbose_name='保底游戏币(w)')),
                ('bomb_extra', models.FloatField(default=0, verbose_name='炸单额外加(w)')),
                ('game_times', models.CharField(blank=True, max_length=50, null=True, verbose_name='对局场次')),
                ('remark', models.CharField(blank=True, max_length=200, null=True, verbose_name='套餐备注')),
                ('creator', models.ForeignKey(db_constraint=False, help_text='创建人', null=True, on_delete=django.db.models.deletion.SET_NULL, related_query_name='creator_query', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
            ],
            options={
                'verbose_name': '三角洲护航价格',
                'verbose_name_plural': '三角洲护航价格',
                'ordering': ['package_type', 'sell_price'],
            },
        ),
    ]
